name: Frontend CI/CD - Docker ECR SSH

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

permissions:
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "153519860425"

  ECR_REPOSITORY: frontend

  BASTION_USER: ec2-user
  PRIVATE_EC2_USER: ec2-user

  CONTAINER_NAME: frontend-container
  CONTAINER_PORT: 80

  IMAGE_TAG: ${{ github.sha }}

jobs:

  build-deploy-frontend:

    runs-on: ubuntu-latest

    steps:

      # --------------------------------------------------
      # 1. Checkout
      # --------------------------------------------------
      - name: Checkout Frontend Source
        uses: actions/checkout@v4


      # --------------------------------------------------
      # 2. Configure AWS credentials
      # --------------------------------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}


      # --------------------------------------------------
      # 3. Verify AWS
      # --------------------------------------------------
      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity


      # --------------------------------------------------
      # 4. Login to ECR
      # --------------------------------------------------
      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2


      # --------------------------------------------------
      # 5. Build Docker Image
      # --------------------------------------------------
      - name: Build Frontend Docker Image
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            ./frontend


      # --------------------------------------------------
      # 6. Push Image to ECR
      # --------------------------------------------------
      - name: Push Frontend Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: |
          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


      # --------------------------------------------------
      # 7. Verify ECR Image
      # --------------------------------------------------
      - name: Verify Frontend Image
        run: |
          aws ecr describe-images \
            --repository-name $ECR_REPOSITORY \
            --image-ids imageTag=$IMAGE_TAG


      # --------------------------------------------------
      # 8. Start SSH Agent
      # --------------------------------------------------
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.BASTION_SSH_PRIVATE_KEY }}


      # --------------------------------------------------
      # 9. Add Bastion Host
      # --------------------------------------------------
      - name: Add Bastion to Known Hosts
        run: |
          mkdir -p ~/.ssh

          ssh-keyscan -H \
            ${{ secrets.BASTION_HOST }} \
            >> ~/.ssh/known_hosts


      # --------------------------------------------------
      # 10. Deploy Through Bastion
      # --------------------------------------------------
      - name: Deploy Frontend Through Bastion
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: |

          ssh -A \
            $BASTION_USER@${{ secrets.BASTION_HOST }} \
            "ssh -A $PRIVATE_EC2_USER@${{ secrets.FRONTEND_PRIVATE_EC2_HOST }} << 'REMOTE_EOF'

              set -e

              echo '========================================'
              echo 'Frontend Deployment Started'
              echo '========================================'

              echo 'Logging into ECR...'

              aws ecr get-login-password \
                --region $AWS_REGION \
                | docker login \
                --username AWS \
                --password-stdin $ECR_REGISTRY

              echo 'Pulling frontend image...'

              docker pull \
                $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

              echo 'Stopping old frontend container...'

              docker stop $CONTAINER_NAME || true

              echo 'Removing old frontend container...'

              docker rm $CONTAINER_NAME || true

              echo 'Starting new frontend container...'

              docker run -d \
                --restart unless-stopped \
                --name $CONTAINER_NAME \
                -p $CONTAINER_PORT:$CONTAINER_PORT \
                $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

              echo 'Waiting for frontend...'

              sleep 15

              echo 'Checking frontend container...'

              docker ps \
                --filter name=$CONTAINER_NAME

              echo '========================================'
              echo 'Frontend Deployment Completed'
              echo '========================================'

          REMOTE_EOF"


      # --------------------------------------------------
      # 11. Success
      # --------------------------------------------------
      - name: Frontend Deployment Successful
        if: success()
        run: |
          echo "Frontend deployment successful."
          echo "Image: $ECR_REPOSITORY:$IMAGE_TAG"


      # --------------------------------------------------
      # 12. Failure
      # --------------------------------------------------
      - name: Frontend Deployment Failed
        if: failure()
        run: |
          echo "Frontend deployment failed."
          echo "Check GitHub Actions logs."



      # --------------------------------------------------
      # build through oidc/ssm
      # --------------------------------------------------

# name: Build and Push Frontend Docker Image to ECR

# on:
#   workflow_dispatch:
#   # push:
#   #   branches:
#   #     - main

# permissions:
#   id-token: write
#   contents: read

# env:
#   AWS_REGION: us-east-1
#   AWS_ACCOUNT_ID: "153519860425"
#   ECR_REPOSITORY: frontend
#   IMAGE_TAG: latest

#   EC2_NAME: docker
#   CONTAINER_NAME: frontend-container
#   CONTAINER_PORT: 8501

# jobs:
#   build-deploy:
#     runs-on: ubuntu-latest

#     steps:

#       # 1. Checkout source code
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       # 2. Authenticate GitHub Actions with AWS using OIDC
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v6
#         with:
#           role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-role
#           aws-region: ${{ env.AWS_REGION }}
#           audience: sts.amazonaws.com

#       # 3. Verify AWS identity
#       - name: Verify AWS Identity
#         run: |
#           aws sts get-caller-identity

#       # 4. Login to ECR
#       - name: Log in to Amazon ECR
#         id: ecr-login
#         uses: aws-actions/amazon-ecr-login@v2

#       # 5. Build and push frontend Docker image
#       - name: Build and Push Frontend Docker Image
#         env:
#           ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
#         run: |
#           docker build \
#             -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
#             ./frontend

#           docker push \
#             $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

#       # 6. Verify image exists in ECR
#       - name: Verify Frontend Image in ECR
#         run: |
#           aws ecr describe-images \
#             --repository-name $ECR_REPOSITORY \
#             --image-ids imageTag=$IMAGE_TAG

#       # 7. Deploy frontend to private EC2 using SSM
#       - name: Deploy Frontend to Private EC2
#         run: |
#           aws ssm send-command \
#             --targets "Key=tag:Name,Values=$EC2_NAME" \
#             --document-name "AWS-RunShellScript" \
#             --comment "Deploy frontend docker image" \
#             --parameters 'commands=[
#               "aws ecr get-login-password --region '$AWS_REGION' | docker login --username AWS --password-stdin '$AWS_ACCOUNT_ID'.dkr.ecr.'$AWS_REGION'.amazonaws.com",
#               "docker pull '$AWS_ACCOUNT_ID'.dkr.ecr.'$AWS_REGION'.amazonaws.com/'$ECR_REPOSITORY':'$IMAGE_TAG'",
#               "docker stop '$CONTAINER_NAME' || true",
#               "docker rm '$CONTAINER_NAME' || true",
#               "docker run -dt --name '$CONTAINER_NAME' -p '$CONTAINER_PORT':'$CONTAINER_PORT' '$AWS_ACCOUNT_ID'.dkr.ecr.'$AWS_REGION'.amazonaws.com/'$ECR_REPOSITORY':'$IMAGE_TAG'"
#             ]' \
#             --region $AWS_REGION

#       # 8. Deployment confirmation
#       - name: Deployment Command Sent
#         run: |
#           echo "Frontend deployment command sent successfully to private EC2."
